# Site settings
title: yuejidaren 
name: yuejdiaren 
email: 
description: ''
baseurl: ""
url: "http://yuejidaren.com"
username: yuejidaren

# Build settings
markdown: kramdown
paginate: 10 
paginate_path: "/p:num"
permalink: /p/:title
